fooof/fit.py, fooof/group.py, fooof/plts.py, fooof/synth.py, fooof/tests/conftest.py, fooof/tests/test_fit.py, fooof/tests/test_group.py, fooof/tests/test_plts.py, fooof/tests/test_synth.py, fooof/tests/test_utils.py, fooof/utils.py, summary.sh
FOOOF Last PR:
Okay, so like actually though, these should be pretty much the last changes. 
Change Log:
- Clean up FOOOFGroup API, by updating so that .load() loads a group file (by aliasing FOOOF.load()), and similarly for .fit() and .save().
- Fix up Group plotting for including knee, including a re-org, increased modularization of plotting methods. This includes moving out some plot templates to a separate file.
- Move synthetic PSD generation outside of test code, so it's more accessible for general use.
- Add some test code, more explicit/modular testing of some functions/methods.
- Make FOOOFResult consistent with FOOOF object - oscillations_params -> oscillation_params
- After hemming and hawing: added _gaussian_params to FOOOFResult object. It makes some back and forth easier (my …
=> Last tweaks

fooof/core/io.py, fooof/core/modutils.py, fooof/core/reports.py, fooof/core/strings.py, fooof/fit.py, fooof/group.py, fooof/plts/fg.py, fooof/plts/fm.py, fooof/plts/templates.py, fooof/tests/test_analysis.py, fooof/tests/test_core_io.py, fooof/tests/test_core_modutils.py, fooof/tests/test_core_utils.py, fooof/tests/test_fit.py, fooof/tests/test_group.py, fooof/tests/test_plts_templates.py, fooof/tests/test_synth.py, fooof/tests/utils.py
These are minor 
These are very much actually just minor updates for v0.1.0, the last things that came up when checking back through the code, and updating tutorials. 
Changelog:
- Improve & clean up tests (in particular IO, get_obj_desc, get_fooof)
- Update gaussian overlap parameter from 1.0 -> 1.5 (units of gaussian bandwidth)
- Add explicit scipy version check 
- Clean up / update what's printed in print_report_issue
- Changes defaults for concise printing to False (this turned out to be quite annoying in the notebook - so now it's optimized for notebook, but can be shortened if desired / for terminal)
- Change name of min_peak_threshold -> peak_threshold (this is a somewhat confusing parameter to start with, and the prior name wasn't super clear and made it even more confusable with …
=> I mean it this time

fooof/synth.py, fooof/tests/test_synth.py
#98 
Note: the test is currently not the greatest but I didn't want to add saved synthetic test data to the repo.
=> added function to perform rotation about axis frequency.

README.md, fooof/core/funcs.py, fooof/core/reports.py, fooof/core/strings.py, fooof/core/utils.py, fooof/fit.py, fooof/group.py, fooof/plts/fg.py, fooof/plts/fm.py, fooof/synth/gen.py, fooof/synth/params.py, fooof/tests/test_core_funcs.py, fooof/tests/test_fit.py, fooof/tests/test_group.py, fooof/tests/test_synth_gen.py, fooof/tests/test_synth_params.py
Update codebase to reflect new naming scheme for 1.0 release. Responds to #77 
This update breaks backwards compatibility with the 0.1.X versions. 
Notes: 
- merge PR #121 first, as this branch includes updates from there. 
- still need to update the pictures, which include figures with outdated labels
=> Update names for 1.0

doc/api.rst, fooof/core/utils.py, fooof/fit.py, fooof/group.py, fooof/synth/gen.py, fooof/synth/params.py, fooof/synth/transform.py, fooof/tests/test_fit.py, fooof/tests/test_group.py, fooof/tests/test_synth_gen.py, fooof/tests/test_synth_params.py, fooof/tests/test_synth_transform.py, fooof/tests/utils.py
Responds to / related to #109
This is a primarily a refactor and extension of fooof.synth.transform. A couple other small updates for naming consistency (using the same convention for gauss*_params between SynParams & gen, and standardizing on calling the ap param 'offset', instead of 'intercept'). 
Notes / comments (mostly Qs for @rdgao):
- Do we know how the knee behaves with these kind of transforms? From quick tests, it appears that, rotating the spectrum does not preserve the knee (which, I think, is to be expected). I'm guessing we can work through figuring out how it does so - though perhaps for now we can just add a note that this is only designed for rotating 'fixed' spectra? (I don't currently need the knee case). 
- I switched the convention for the direction of rotation, so …
=> Refactor & update fooof.synth.transform

README.md, doc/api.rst, doc/faq.rst, examples/plot_synthetic_power_spectra.py, fooof/analysis.py, fooof/core/funcs.py, fooof/core/info.py, fooof/core/strings.py, fooof/data.py, fooof/fit.py, fooof/group.py, fooof/plts/fm.py, fooof/synth/gen.py, fooof/tests/test_analysis.py, fooof/tests/test_core_funcs.py, fooof/tests/test_group.py, tutorials/plot_01-ModelDescription.py, tutorials/plot_02-FOOOF.py, tutorials/plot_03-FOOOFAlgorithm.py, tutorials/plot_04-MoreFOOOF.py, tutorials/plot_06-FOOOFGroup.py, tutorials/plot_07-TroubleShooting.py, tutorials/plot_08-FurtherAnalysis.py
Responds to #131 
Notable changes (in code):
- Public setting `min_peak_amplitude` -> `min_peak_height`
- Private setting `_ap_amp_thresh` -> `_ap_percentile_thresh`
- Reference to 'Amp' as a usable label to select data -> 'PW' (for power)
Notable changes (in documentation / tutorials):
- Where possible, most references to 'amplitude' things have been made agnostic, referring to 'height' instead of using the words 'amplitude' or 'power'. 
- Where in reference to extracted peaks in particular, the word 'power', with abbreviation 'PW' is used. 
This is in context of labelling peaks as {'CF': center frequency, 'PW': power, 'BW': bandwidth}
- Through doing this, I noticed some inconsistencies of when things are referred to as 'peaks' vs 'gaussians', so some updates (in documentation / …
=> Update reference to 'amp' & 'amplitude' -> 'height' or 'power'

.gitignore, examples/plot_mne_example.py
@TomDonoghue asked me to work on an example of plotting topologies using mne.
=> 1st draft of mne example

doc/faq.rst, doc/glossary.rst, examples/analyses/plot_mne_example.py, examples/manage/plot_fit_fooof_3d.py, examples/manage/plot_manipulating_fooofs.py, examples/plots/plot_model_components.py, examples/plots/plot_power_spectra.py, examples/sims/plot_sim_params.py, examples/sims/plot_transforms.py, fooof/analysis/periodic.py, fooof/sim/transform.py, fooof/utils/data.py, motivations/concepts/plot_DoYouEvenOscillate.py, motivations/concepts/plot_IfYouFilterTheyWillCome.py, motivations/measurements/plot_BandByBand.py, tutorials/plot_01-ModelDescription.py, tutorials/plot_02-FOOOF.py, tutorials/plot_03-FOOOFAlgorithm.py, tutorials/plot_05-AperiodicFitting.py, tutorials/plot_06-FOOOFGroup.py
This issue relates to #167, which is a review of the documentation site. 
Changes:
- fixes typos found in motivations, tutorials, examples, docstrings, and faq sections.
=> FIX: Fix typos in the documentation site.

fooof/objs/fit.py
So far, the CF of one peak had been compared to the lower bound of the next gaussian. This PR fixes this so that the upper bound of one guassian is compared to the lower bound of the next. This may require adjustment to `_gauss_overlap_thresh`.
=> [FIX] Bounds incorrect in _drop_peak_overlap.

requirements.txt, setup.cfg, setup.py
A small set up of updates related to managing the module.
=> Small module related updates

fooof/objs/fit.py, fooof/objs/group.py, fooof/objs/utils.py, fooof/tests/objs/test_fit.py
Responds to #175 
This PR adds the `check_data` mode to FOOOF objects, which controls if added data is checked for NaN/Inf data-points, and fails out if so. By default, `check_data` is turned on, in which case objects act the same as before. 
However, this mode can be turned off, in which case the object plays nice with having NaN/Inf data. Model fitting will cleanly fail (no error) and so fitting can continue. This allows for fitting groups of spectra in which some spectra are NaN, and makes it easier to deal with messy shaped data in which some spectra may be missing, etc. 
So far the decision here is to not change default behaviour, but add an option for users to bypass some of the data checks. This, I think, is a safer option - the user has to choose when to ignore NaN data, and …
=> [ENH] Add `check_data` mode to deal with running with/without nan values

doc/conf.py, motivations/concepts/plot_DoYouEvenOscillate.py, motivations/concepts/plot_IfYouFilterTheyWillCome.py
The neurodsp imports in motivations now links to the neurodsp site. This is related to voytekresearch/VoytekLabPrivate#7.
=> [DOC] Intersphinx link to neurodsp

fooof/objs/fit.py, fooof/objs/group.py
As mentioned in this issue (#192) - there is a deprecation with newer numpy on how we were managing peak parameters in FOOOFGroup.get_params. Issue was we were calling `np.array` on a list of array. This can simply be replaced by `np.vstack`, to avoid the issue with typecasting the messy list object to an array.
=> [MNT] - Update peak extraction array & describe index column

fooof/core/utils.py, fooof/objs/fit.py, fooof/objs/utils.py, fooof/tests/objs/test_utils.py
Addresses a point in #193. This adds minor tweaks to speed up fitting. The most noticeable difference is when using `fit_fooof_3d`. 56% faster for a (100, 10, 99) array:
```python
import numpy as np
from fooof import FOOOFGroup
from fooof.objs import fit_fooof_3d
from fooof.sim import gen_group_power_spectra
np.random.seed(0)
ap_params = [-2, 0]
pe_params = [[10, 5, 5], [25, 5, 5]]
freqs, powers = gen_group_power_spectra(10, (1, 50), ap_params, pe_params)
powers_3d = np.array([powers] * 100)
fg = FOOOFGroup(verbose=False)
```
```python
%%timeit
fgs = fit_fooof_3d(fg, freqs, powers_3d, n_jobs=4)
```
Before:
> 3.56 s ± 20.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
After:
> 2 s ± 19.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
=> [ENH] Optimization

doc/conf.py, examples/processing/README.txt, examples/processing/plot_line_noise.py, fooof/tests/utils/test_data.py, fooof/utils/data.py
A common question is how to deal with line noise, and so I started collecting my responses to turn into a proper example, which I finally fixed up and is added here. 
In the process, I ended up updating `interpolate_spectrum` a bit to support multiple interpolation zones.
I think everything here should be relatively straight-forward - @ryanhammonds, it would be great if you could read through the example for wording quirks, and check that the code updates make sense to you. Thanks!
=> [DOC] - Add a line noise example

doc/api.rst, examples/analyses/plot_mne_example.py, examples/plots/plot_power_spectra.py, examples/sims/plot_simulated_power_spectra.py, fooof/plts/__init__.py, fooof/plts/annotate.py, fooof/plts/error.py, fooof/plts/fm.py, fooof/plts/spectra.py, fooof/tests/plts/test_spectra.py, motivations/measurements/plot_BandRatios.py, tutorials/plot_01-ModelDescription.py, tutorials/plot_03-FOOOFAlgorithm.py
This addresses a point in #193. `plot_spectra` not accepts 1d arrays and `plot_spectrum` has been replaced by `plot_spectra` throughout the module. The same has been done with `plot_spectra_shading`, with `plot_spectrum_shading` removed.
Also, `plot_spectrum` has been aliased to `plot_spectra` in the \_\_init\_\_.py to not break anyone's code. This wasn't done for `plot_spectrum_shading` since it's not imported in the init.
=> [ENH] Combined plot_spectra and plot_spectrum

fooof/plts/utils.py, fooof/tests/plts/test_utils.py
Follows the model of https://github.com/neurodsp-tools/neurodsp/pull/258
=> [ENH] - Update savefig default to save when given file_name

fooof/objs/fit.py
Short version: the fixed line ended up with an extra layer of embedded lists which led to downstream problems. 
The longer version (why it's a problem):
In practice, we never bound the aperiodic fits, but in theory one could, by update `_ap_bounds`. However - if one tried to do this, then the fitting actually gets kicked to a different approach, which then checks that the guess parameters are 1d. This would then fail, because the embedded list made them 2d. This PR fixes that.
Note that this change doesn't change anything that happens in standard usage - but will make it possible to add `_ap_bounds`, in which case what happens in the fitting is slightly different.
=> [BUG] - Fix embedded lists for ap_fit guess

fooof/objs/fit.py
Someone emailed to point out that the guess exponent estimation, line 745 of fit, looks to have missing parentheses. What should be `[abs((a-b) / (c-d))]` was actually `[abs( a - b / c - d )]`, meaning the calculated value is wrong (is not the slope estimate we want it to be. This fixes that. 
Note that the exponent guess is just an initial value into curve_fit. In all my checks on this, fixing this makes literally zero difference to the model solution - so this shouldn't impact any fits in practice.
=> [BUG] - Fix estimation of the exponent guess

fooof/plts/annotate.py
Iterations in annotated plots are currently plotted by by ascending center frequency, rather than descending peak height (i.e. the order of the peak search). Someone emailed confused about this. I've fixed it here.
Before:
After:
=> [BUG] Annotated Plots

fooof/core/modutils.py
There was a bug in `check_dependency` that wouldn't return the outputs of the returned function. Within specparam, this never really came up, since we use this for plot functions (with no returns). Therefore, this fix makes the function do what it is supposed to do - but should currently have no impact on anything already using `check_dependency` within the module.
=> [BUG] - Fix return in check_dependency

examples/analyses/plot_mne_example.py, requirements-docs.txt
MNE 1.3 has fully deprecated `psd_welch`. Following the MNE 1.2 deprecation suggestion: https://mne.tools/1.2/generated/mne.time_frequency.psd_welch.html , I replaced it with `.compute_psd(method="welch")`
Additionally, paths are now returned using `pathlib.Path`, not `str`.
I ran this locally to check, and it works with MNE 1.3.1
=> Fix MNE example to work with MNE 1.3

fooof/core/strings.py
It turns out in our bandwidth limits warning, the variables were flipped such that it printed out wrong. 
For example, with a frequency resolution of 1, and a bandwidth limit of 0.5, the current code would print:
`FOOOF WARNING: Lower-bound peak width limit is < or ~= the frequency resolution: 1.00 <= 0.50`
Which is unhelpfully wrong... 
This PR fixes this, by switching the variables to report properly. From my checks, I think it is just the warning that prints out wrong - the actual checks of the values seem correct.
This responds to this issue as reported in #244
=> [MNT] - Fix order of reporting values in bw limits warning

fooof/core/reports.py, fooof/objs/fit.py, fooof/objs/group.py, fooof/plts/fg.py, fooof/plts/fm.py
Responds to #218 
Main updates:
- adds settings to a saved out FOOOFGroup report
- adds the option to choose whether settings are saved for saving out both FOOOF and FOOOFGroup reports
- tweaks some sizing to make the reports work / look good
- adds the option to pass in explicit figure sizes for model plots
Note: for review, the code changes here are fairly simple - but it would be useful to check that when running the report generation code locally, that the sizing and layout looks alright!
=> [MNT] - Update reports (add settings)

README.rst, fooof/core/modutils.py, fooof/data/conversions.py, fooof/objs/fit.py, fooof/objs/group.py, fooof/tests/conftest.py, fooof/tests/data/test_conversions.py, fooof/tests/objs/test_fit.py, fooof/tests/objs/test_group.py, fooof/tests/tutils.py, optional-requirements.txt
Adds `fooof.data.conversions` that allows for converting model results into alternate forms, including DataFrames.
A key component for doing this is to is to organize how to to organize peaks. Currently, this implementation supports organizing a set number of peaks, or using band definitions.
Note that this is an alternate approach to some other ideas explored in #194 
Example usage:
```
from fooof import FOOOFGroup, Bands
from fooof.sim import gen_group_power_spectra
freqs, pows = gen_group_power_spectra(2, [3, 40], [1, 1], [[10, 1, 1], [20, 1, 1]])
fg = FOOOFGroup(verbose=False)
fg.fit(freqs, pows)
```
```
fg.to_df(2)
```
```
bands = Bands({'alpha' : [8, 12], 'beta' : [15, 30]})
fg.to_df(bands)
```
=> [ENH] - Add support for converting model results, including to DFs

fooof/objs/fit.py, fooof/tests/objs/test_fit.py
This adds an explicit check when data added that the frequency vector is evenly spaced (equidistant points in linear space). The goal is to check and exclude situations in which there are gaps in frequencies (which could interact weirdly with things like the peak fitting). 
Note that this check can be turned off by setting the `_check_freqs` private attribute to False
Note: Related to #237, which brought up how unevenly spaced frequency values can lead to failures down the line.
=> [MNT] - Add `check_freqs` to check for uneven frequency samples

fooof/__init__.py
- Check the language.
- We might also want to add an explicit link to the specparam project as well, but that's maybe overkill for a warning message.
=> add deprecation warning

README.rst
Nowadays, I think our recommendation if one is in Matlab is to use it through Fieldtrip or Brainstorm, right? Assuming so, this updates the README to note this, plus a bit more info on known ways to use specparam outside Python. 
Sidenote: since this is going in now to the 1.1 tag, it still says `fooof`, but this will be changed to `specparam` when merged to the name branch.
=> [DOC] - Update README listing of other language support

fooof/objs/fit.py, fooof/objs/utils.py
Small set of code updates from running linting. 
Main changes:
- Errors that are raised from an exception are now 'raised from' (https://stackoverflow.com/questions/24752395/python-raise-from-usage)
- some list comprehensions switched to be generator comprehension (https://stackoverflow.com/questions/47789/generator-expressions-vs-list-comprehensions)
=> [MNT] - Minor updates from linting

doc/changelog.rst
PR for updates to the changelog - this part has notes on the new 1.1.0 version.
=> [DOC] - Update changelog

fooof/core/strings.py, fooof/objs/group.py
Couple small fixes:
- in `FOOOFGroup`, update the docs to match that the attributes are called `n_null_` and `null_inds_`
- in report generation, use the `n_null_` attribute instead of counting missing exponents
=> [MNT] - Small fix up for null models

fooof/core/modutils.py, fooof/objs/group.py, fooof/tests/conftest.py, fooof/tests/core/test_modutils.py, fooof/tests/tutils.py
This is an update adding more functionality to programmatically managing docstrings, with the overall goal of being able to copy around docstrings sections automatically instead of copy / pasting in the source code. 
This is a somewhat forward looking update (will be more useful / important as we add more objects that may share parameters, etc), but here already gets used with the FOOOFGroup object to copy over sections. 
In terms of reviewing, it's mostly annoying string manipulation, and any thoughts are more than welcome - but in terms of evaluating functionality, I checked that this works when building the docsite, which is what I'm largely using to check that this ultimately work:
This is the built docsite page for FOOOFGroup:
This show what the source code page shows (showing the …
=> [MNT] - Update docstring handling to do more copying around / reduce copied text

fooof/tests/settings.py
The `pkg_resources` API, which comes with `setuptools` is being deprecated (see warning here: https://setuptools.pypa.io/en/latest/pkg_resources.html). Since we only use this to get the path for the test outputs (and moving to use `importlib` is a bit annoying across multiple python version - see here: https://stackoverflow.com/a/75503824), this update gets away with this entirely, and gets the needed path with just `os` and `pathlib`. 
In terms of review - key questions is whether it works properly / consistently across systems. It works for me locally and on Github Actions - so that seems promising. @ryanhammonds - can you check if this works for you on your system? If so, I think this should be okay to go with.
=> [MNT] - Drop use of package_resources

fooof/data/conversions.py, fooof/tests/data/test_conversions.py
Add `group_to_dict` function to `data.conversions`. 
The allows for exporting group results to a dictionary representation, which can then be used as a faster way to go from group results -> dataframe.
=> [ENH] - Add and use `group_to_dict` function

MANIFEST.in, Makefile
Continuing the updates for things that are changing in the Python ecosystem - this updates away from calling `setup.py` directly in the build process, as this is now suggested against. 
New versions of `setuptools` print this out when running our current build command (`python setup.py sdist bdist_wheel`):
Link: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
I didn't do the deep dive - but there is a useful table that indicates the new approach, using 
https://github.com/pypa/build
Related to which, this PR:
- updates the Makefile to use `build` to create the distribution
- adds the `requirements.txt` to the MANIFEST.in
- it should probably have been in there (`build` needs it, as it builds the distribution in a venv)
Comparing the output distribution files, as far as I …
=> [MNT] - Update build procedure

fooof/core/reports.py, fooof/plts/fg.py, fooof/plts/settings.py, fooof/plts/style.py, fooof/plts/templates.py
This is a set of minor updates to plotting and styling. 
One goal is to reduce the number of warnings that are popping up - in particular around applying tight_layout, and the warnings that became more common saying "this figure can't have that". In doing so, it tweaks how plot style functions get applied (allowing for passing in None's to turn them off). It also updates how styling gets applied to group report plots, as the previous approach had issues with the twinned axes (would only get one of them, leading to different label sizes). 
In part, this relates to at some point, something external seeming to have changed in terms of interpreting the figure sizes, such that our figures now seem to be printed bigger (?). This seems to be version specific - the current PR tweaks sizes to look …
=> [MNT] - Plot & report tweaks

doc/api.rst, fooof/core/modutils.py, fooof/tests/core/test_modutils.py, fooof/tests/utils/test_data.py, fooof/utils/data.py
This is a minor update that adds a convenience function, `interpolate_spectra`, that can be directly applied to interpolate away frequency regions across a group of power spectra.
To do so, it wraps `interpolate_spectrum` so it can be applied across an array of PSDs. 
This PR also includes a minor update to `docs_get_section` to assist in copying over information. 
Adding this was mentioned here: https://github.com/fooof-tools/fooof/pull/203#discussion_r611920788
=> [ENH] - Add `interpolate_spectra` function

doc/api.rst, fooof/objs/utils.py, fooof/plts/__init__.py, fooof/plts/spectra.py, fooof/tests/objs/test_utils.py
Adds a new `average_reconstructions` function as a minor helper function - an addition mentioned in #227 
Note: the last commit is unrelated to the new function - it's just a small update to the aliasing of `plot_spectrum` to `plot_spectra` - moving this alias to the file means that `from fooof.plts.spectra import plot_spectrum` should work now whereas is would fail otherwise.
=> [ENH] - Add `average_reconstructions` function

specparam/plts/aperiodic.py, specparam/plts/periodic.py, specparam/plts/templates.py
Minor update to allow for plotting shades around average for model reconstructions (as mentioned in #227)
Note: this PR is directed to merge into the `time` branch, and then be in 2.0, since it uses the refactored `plot_yshade` function, and so does not easily go into 1.1.
=> [ENH] - Add options to shade param reconstructions

examples/analyses/plot_dev_demo.py
This adapts the Developmental Data example, from [here](https://github.com/fooof-tools/DevelopmentalDemo) into an example to be hosted on the documentation website. 
In terms of content, it's about the same, just edited in format for hosting, and with some mild updates to match current version 1.1.
For ease of checking / reviewing - here is a copy of the built documentation including what's added:
[html.zip](https://github.com/fooof-tools/fooof/files/12065021/html.zip)
^If you download and unzip this, it's a copy of the built documentation page. Open the html folder, and double click 'index.html' to open the home page in a browser. Then you can click on the examples tab, and under the analyses section, click and see the new "Developmental Data Demo" example.
=> [DOC] - Add Developmental Demo to the docsite examples page

fooof/objs/fit.py, fooof/plts/fm.py, fooof/plts/spectra.py, fooof/tests/plts/test_fm.py
Responds to #245, and an alternative to #246
This PR adds functionality for making it easier to plot a model over a broader frequency range (across a frequency range beyond the fit range). It does so by making it easier to pass in frequency and power vectors to plot with a model. This strategy means that the model object does not store the broader range, but during exploration phases this can be visualized. 
Notes:
- This strategy generally means the broader range spectrum needs to be "around" (in memory) to be passed in explicitly. 
- A limitation of this is that if a fooof object is reloaded, the broader range spectrum while not de facto be available for this.
- The upshot of this is trying to find a balance between supporting evaluation without increasing the amount of data stored in …
=> [ENH] - Update options to plot a broader frequency range

fooof/core/info.py, fooof/data/data.py, fooof/objs/fit.py, fooof/objs/group.py
This fix adds setters and getters for run_modes in fooof objects in fit.py. The dictionary returned by get_description() in info.py includes attributes for all run_modes. The get_fooof() and get_group() functions in group.py are now updated to probably transfer run mode settings from the current object to newly instantiated objects. Documentation relating to run_modes was updated in all files.
This Pull Request relates to this [issue](https://github.com/fooof-tools/fooof/issues/292).
=> Create setters/getters for check modes and fix management

fooof/sim/params.py
This tweaks the checks on the Stepper object to allow for using the Stepper object to step along decreasing parameter values.
For example, this would have previously raised an error, but now works:
`exp_stepper = Stepper(2.5, 0.5, -0.25)`
=> [MNT] - Update parameter Stepper object

examples/models/plot_data_components.py, fooof/core/utils.py, fooof/objs/fit.py, fooof/tests/core/test_utils.py, fooof/tests/objs/test_fit.py
This PR is an exploration related to our broader topic / discussion regarding the 'spacing' of the data, relating to whether we want, for example, parameter values in log or linear spaced values, and whether we want to have a compositional model which adds the components in log or linear space. This PR deals with the isolated data & model components. 
The `FOOOF` object stores the data, resulting model, as well as internal attributes of isolated data & model components. 
Specifically:
- "data" attributes:
- 'full' data: `FOOOF.power_spectrum`
- 'aperiodic only' data: `FOOOF._spectrum_peak_rm`
- 'periodic only' data: `FOOOF._spectrum_flat`
- "model" attributes:
- 'full' model: `FOOOF.fooofed_spectrum_`
- 'aperiodic only' data: `FOOOF._ap_fit`
- 'periodic only' data: `FOOOF._peak_fit`
These …
=> [ENH] - Add getter functions for data & model components

fooof/core/funcs.py, fooof/core/jacobians.py, fooof/objs/fit.py, fooof/tests/core/test_jacobians.py, fooof/tests/objs/test_fit.py
This is a series of small tweaks to the fit algorithm that should result in minor improvements in run speed. 
Updates include:
- a slightly more efficient stepping across params in gaussian function
- removing unneeding 'ys' initialization in aperiodic fit functions
- setting `check_finite` to False in curve_fit (since we do our own data checking)
- expose `curve_fit` tolerance settings as a private setting, and set new default value that is a bit more liberal
- provide precomputed Jacobian matrix, for the Guassian curve_fit call*
*I did add the Jacobians for the AP functions as well, but there was more mixed results whether this provided any speedup - notably these calls are already pretty fast, and so based on [this](https://stackoverflow.com/questions/24391242/scipys-curve-fit-leastsq-b …
=> [MNT] - Optimizations for curve fit

fooof/tests/utils/test_params.py, fooof/utils/params.py
We have a function the repo to estimate 'timescales', added in here. I happened to notice that the function we have here described the calculation as being estimated from the knee _parameter_, whereas Richard's work estimates it from the knee _frequency_ - which I assume is correct? If so, this is currently incorrectly described here, and this PR updates that.
This is what I'm following from Richard's work: 
https://github.com/rdgao/field-echos/blob/master/echo_utils.py#L65
I know the "knee frequency" calculation is an estimation - this function should at least be updated to describe the correct parameter - should we also add a bit of note describing it more and/or referencing this to Richards paper? Thoughts, @rdgao?
=> [BUG] - Fix description of time constant estimation

doc/api.rst, fooof/objs/fit.py, fooof/plts/aperiodic.py, fooof/plts/error.py, fooof/plts/fg.py, fooof/plts/fm.py, fooof/plts/periodic.py, fooof/plts/settings.py, fooof/plts/spectra.py, fooof/plts/style.py, fooof/tests/plts/test_styles.py
Minor update to managing style of PSD plots to allow for passing in and controlling whether there is a grid or not.
=> [MNT] - Make grid an updateable argument in PSD plots

fooof/__init__.py, fooof/version.py
We previously set the deprecation warning to an "always" filter, however this has unintended consequences - it voids user's own filters, so it makes the warning impossible to turn off. If running code in parallel, this can lead to it being practically impossible to stop the warning being printed multiple times, making it _very_ annoying. I think we shouldn't be over-riding users own warnings settings - so this removes the "always" filter. 
Also - bump version to rc3!
=> [MNT] - Update deprecation warning

specparam/plts/settings.py, specparam/plts/style.py
`matplotlib` is an optional dependency, but it is a required dependency as follows.
```
$  python -c "import specparam"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "*/python3.12/site-packages/specparam/__init__.py", line 6, in <module>
from .objs import SpectralModel, SpectralGroupModel, SpectralTimeModel, SpectralTimeEventModel
File "*/python3.12/site-packages/specparam/objs/__init__.py", line 3, in <module>
from .model import SpectralModel
File "*/python3.12/site-packages/specparam/objs/model.py", line 10, in <module>
from specparam.objs.base import BaseObject
File "*/python3.12/site-packages/specparam/objs/base.py", line 14, in <module>
from specparam.objs.results import BaseResults, BaseResults2D, BaseResults2DT, BaseResults3D
File …
```
=> Fixed matplotlib is required

.github/workflows/build.yml
So this keeps the lights on for now for testing Python 3.7, though I think it might stop working again soon, so we might need to make some decisions on what Python versions we officially support / test against.
=> [MNT] - try new ubuntu tagged test version for py37

specparam/core/strings.py, specparam/utils/data.py
Responds to #340 - see discussion there
=> [MNT] - Fix presence report printing for consistency

specparam/core/funcs.py, specparam/objs/fit.py, specparam/sim/gen.py
Hello!
This library is very helpful, I added a lorentzian function to the periodic fit capability because I use this for modeling peaks in power density spectra of black hole light curves, it might be useful for other areas as well :)
http://emilygraceripka.com/blog/16
=> added lorentzian function

specparam/modes/mode.py, specparam/tests/modes/test_mode.py
This commit basically belongs to #298
=> [ENH] - Add missing commit from modes update
